name: PHPUnit

on: pull_request

jobs:
  test:
    name: PHPUnit (PHP ${{ matrix.php-versions }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.4"]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Composer cache
        id: composer_cache
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install composer
        shell: bash
        if: steps.composer_cache.outputs.cache-hit != 'true'
        run: |
          echo 'Install packages'
          composer install -n --prefer-dist

      - name: Run phpunit
        run: composer tests
